services:
  taskins:
    build:
      context: .
      args:
        INSTALL_DEV: "true"
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    container_name: taskins-app
    env_file: .env.dev
    ports:
      - "80:80"
    volumes:
      - taskins-db-dev:/app/data
      - ./secrets:/app/secrets:ro
      - .:/app
    networks:
      - taskins-net
    command: uvicorn taskins.main:app --host 0.0.0.0 --port 80 --reload

volumes:
  taskins-db-dev:
    name: taskins-db-dev

networks:
  taskins-net:
    name: taskins-net
